import HeaderNavigation from "@/components/header-nav";
import type { Metadata } from "next";
import { getAuthenticatedAppForUser } from "@/lib/firebase/serverApp";

export const metadata: Metadata = {
  title: "Someone should make",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { currentUser } = await getAuthenticatedAppForUser();

  return (
    <>
      <HeaderNavigation initialUser={currentUser?.toJSON()} />
      {children}
    </>
  );
}
