import HeaderNavigation from "@/components/header-nav";
import type { Metadata } from "next";
// import localFont from "next/font/local";
// import "./globals.css";

// const clashDisplay = localFont({
//   src: '../public/fonts/ClashDisplay-Variable.ttf',
//   variable: '--font-clash-display'
// });

export const metadata: Metadata = {
  title: "Someone should make",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <HeaderNavigation />
      {children}
    </>
  );
}
